+ bug fixed when GZIP environment variable was set + several tiny changes and fixes

diff --git a/gz2bz b/gz2bz
--- a/gz2bz
+++ b/gz2bz
@@ -1,7 +1,7 @@
 #!/bin/sh
 ##
 ## gzip to bzip2 converter
-## $Id: gz2bz,v 1.3 2006/09/28 15:06:19 mina86 Exp $
+## $Id: gz2bz,v 1.4 2006/10/02 17:47:47 mina86 Exp $
 ## Copyright (c) 2005 by Michal Nazareicz (mina86/AT/mina86.com)
 ##
 ## This program is free software; you can redistribute it and/or modify
@@ -27,8 +27,8 @@ set -e
 ## Version
 ##
 version () {
-	echo 'gz2bz  ver. 0.1   (c) 2005 by Michal Nazarewicz (mina86/AT/mina86.com)'
-	echo '$Id: gz2bz,v 1.3 2006/09/28 15:06:19 mina86 Exp $'
+	echo 'gz2bz   (c) 2005 by Michal Nazarewicz (mina86/AT/mina86.com)'
+	echo '$Id: gz2bz,v 1.4 2006/10/02 17:47:47 mina86 Exp $'
 	echo
 }
 
@@ -54,7 +54,7 @@ usage: gz2bz <options> [ [--] file ...]
  -G --gzip=<gzip>       Uses <gzip> as gzip executable               [auto]
  -g --gzip-opts=<opts>  Adds aditional arguments to gzip             [none]
  -B --bzip2=<bzip2>     Uses <bzip2> as bzip2 executable             [auto]
- -b --bzip2-opts=<opts> Adds aditional arguments to bzip2            [auto]
+ -b --bzip2-opts=<opts> Adds aditional arguments to bzip2            [none]
 
  -k --keep              Keeps uncompressed file
     --keep-gz           Keeps .gz file
@@ -78,7 +78,7 @@ VERBOSE=
 ##
 ## Parse args
 ##
-while [ $# -ne 0 ] && [ "X$1" != X-- ]; do
+while [ $# -ne 0 ] && [ X"$1" != X-- ]; do
 	case "$1" in
 	(-h|--help)    usage  ; exit; ;;
 	(-V|--version) version; exit; ;;
@@ -116,58 +116,58 @@ while [ $# -ne 0 ] && [ "X$1" != X-- ]; do
 	esac
 	shift
 done
-if [ "X$1" = X-- ]; then shift; fi
+[ X"$1" != X-- ] || shift
 
 
 ##
 ## Find executables, etc
 ##
 find_exec () {
-	if [ "X$2" = Xauto ]; then __SEARCH="$1"; else __SEARCH="$2"; fi
-	if ! __FOUND=$(which "$__SEARCH" 2>/dev/null); then
-		echo "${0##*/}: Could not find gzip executable:" >&2
-		which "$__SEARCH" >&2
+	if [ "X$3" = Xauto ]; then __SEARCH="$2"; else __SEARCH="$3"; fi
+	if ! __FOUND=$(which "$__SEARCH"); then
+		echo "${0##*/}: Could not find $2 executable:" >&2
 		exit 2
 	fi
-	printf "%s" "$__FOUND"
+	eval $1=\"\$__FOUND \$4\"
 }
 
-GZ="$(find_exec gzip "$GZIP") $GZIP_OPTS -d"
-BZ2="$(find_exec bzip2 "$BZIP2") $BZIP2_OPTS"
+# find_exec VAR  def-exec opt-exec  opts
+find_exec   GZ   gzip     "$GZIP"   "$GZIP_OPTS -d"
+find_exec   BZ2  bzip2    "$BZIP2"  "$BZIP2_OPTS"
+unset GZIP GZIP_OPTS BZIP2 BZIP2_OPTS
 
 
 ##
 ## Do the job
 ##
-if [ $# -eq 0 ]; then set -- -; fi
-while [ $# -ne 0 ]; do
+[ $# -ne 0 ] || set -- -
+for FILE; do
 	## stdin
-	if [ "X$1" = X- ]; then
-		if [ -n "$VERBOSE" ]; then echo Converting stdin to stdout; fi
+	if [ X"$FILE" = X- ]; then
+		[ -z "$VERBOSE" ] || echo Converting stdin to stdout
 		$GZ | $BZ2 || true
-		shift
 		continue
 	fi
 
 	## Get output file name
-	  if [ "X${1%.tgz}" != "X$1" ]; then OUTPUT="${1%.tgz}.tar"
-	elif [ "X${1%.gz}"  != "X$1" ]; then OUTPUT="${1%.gz}"
-	else echo "${0##*/}: $1: invalid extension, skipping"; shift; continue
-	  fi
+	case "$FILE" in
+	(*.tgz) OUTPUT="${FILE%.tgz}.tar" ;;
+	(*.gz)  OUTPUT="${FILE%.gz}" ;;
+	(*) echo "${0##*/}: $FILE: invalid extension, skipping"; continue
+	esac
 
 	## Header
-	if [ -n "$VERBOSE" ]; then echo Converting "$1" to "$OUTPUT.bz2"; fi
+	[ -z "$VERBOSE" ] || echo Converting "$1" to "$OUTPUT.bz2"
 
 	OK=y
 	## Convert
 	if [ -n "$KEEP_UNCOMPRESSED" ]
-	then $GZ <"$1" >"$OUTPUT" && $BZ2 <"$OUTPUT" >"$OUTPUT.bz2" || OK=
-	else $GZ <"$1" | $BZ2 >"$OUTPUT.bz2" || OK=
+	then $GZ <"$FILE" >"$OUTPUT" && $BZ2 <"$OUTPUT" >"$OUTPUT.bz2" || OK=
+	else $GZ <"$FILE" | $BZ2 >"$OUTPUT.bz2" || OK=
 	fi
 
 	## Finish
-	if [ -z "$OK" ]; then echo "${0##*/}: $1: failed"
-	elif [ -z "$KEEP_GZ" ]; then rm -f -- "$1" || true
+	if [ -z "$OK" ]; then echo "${0##*/}: $FILE: failed"
+	elif [ -z "$KEEP_GZIP" ]; then rm -f -- "$FILE" || true
 	fi
-	shift
 done
