+bug fixed

diff --git a/gz2bz b/gz2bz
--- a/gz2bz
+++ b/gz2bz
@@ -1,7 +1,7 @@
 #!/bin/sh
 ##
 ## gzip to bzip2 converter
-## $Id: gz2bz,v 1.1 2005/11/20 20:25:23 mina86 Exp $
+## $Id: gz2bz,v 1.2 2005/11/22 21:29:19 mina86 Exp $
 ## Copyright (c) 2005 by Michal Nazareicz (mina86/AT/tlen.pl)
 ##
 ## This program is free software; you can redistribute it and/or modify
@@ -28,7 +28,7 @@ set -e
 ##
 version () {
 	echo 'gz2bz  ver. 0.1   (c) 2005 by Michal Nazarewicz (mina86/AT/tlen.pl)'
-	echo '$Id: gz2bz,v 1.1 2005/11/20 20:25:23 mina86 Exp $'
+	echo '$Id: gz2bz,v 1.2 2005/11/22 21:29:19 mina86 Exp $'
 	echo
 }
 
@@ -132,7 +132,7 @@ find_exec () {
 	printf "%s" "$__FOUND"
 }
 
-GZ="$(find_exec gzip "$GZIP") $GZIP_OPTS"
+GZ="$(find_exec gzip "$GZIP") $GZIP_OPTS -d"
 BZ2="$(find_exec bzip2 "$BZIP2") $BZIP2_OPTS"
 
 
@@ -144,7 +144,7 @@ while [ $# -ne 0 ]; do
 	## stdin
 	if [ "X$1" = X- ]; then
 		if [ -n "$VERBOSE" ]; then echo Converting stdin to stdout; fi
-		GZ | BZ2 || true
+		$GZ | $BZ2 || true
 		shift
 		continue
 	fi
@@ -161,12 +161,13 @@ while [ $# -ne 0 ]; do
 	OK=y
 	## Convert
 	if [ -n "$KEEP_UNCOMPRESSED" ]
-	then $GZ <"$1" >"$OUTPUT" && $BZ <"$OUTPUT" >"$OUTPUT.bz2" || OK=
-	else $GZ <"$1" | $BZ >"$OUTPUT.bz2" || OK=
+	then $GZ <"$1" >"$OUTPUT" && $BZ2 <"$OUTPUT" >"$OUTPUT.bz2" || OK=
+	else $GZ <"$1" | $BZ2 >"$OUTPUT.bz2" || OK=
 	fi
 
 	## Finish
-	if [ -n "$OK" ] && [ -z "$KKEP_GZ" ]; then rm -f -- "$1" || true; fi
-	if [ -z "$OK" ]; then echo "${0##*/}: $1: failed"; fi
+	if [ -z "$OK" ]; then echo "${0##*/}: $1: failed"
+	elif [ -z "$KEEP_GZ" ]; then rm -f -- "$1" || true
+	fi
 	shift
 done
