+ --config option added

diff --git a/installkernel b/installkernel
--- a/installkernel
+++ b/installkernel
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##
 ## installkernel - Script for installing Linux kernel.
-## $Id: installkernel,v 1.15 2005/08/13 13:22:26 mina86 Exp $
+## $Id: installkernel,v 1.16 2005/08/18 01:45:41 mina86 Exp $
 ## Copyright (c) 2004,2005 by Michal Nazarewicz (mina86/AT/tlen.pl)
 ##
 ## This program is free software; you can redistribute it and/or modify
@@ -23,8 +23,8 @@
 ## Version
 ##
 if [ ! $INSIDE_INSTALLKERNEL ]; then
-	echo 'installkernel  v0.11  (c) 2004,2005 by Micha³ Nazarewicz'
-	echo '$Id: installkernel,v 1.15 2005/08/13 13:22:26 mina86 Exp $'
+	echo 'installkernel  v0.12  (c) 2004,2005 by Micha³ Nazarewicz'
+	echo '$Id: installkernel,v 1.16 2005/08/18 01:45:41 mina86 Exp $'
 	echo
 	if [ -f /tmp/installkernel-lockfile ]; then
 		echo "${0##*/}: lockfile exists"
@@ -35,10 +35,11 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 			echo "${0##*/}: or remove /tmp/installkernel-lockfile if that is the case"
 			exit 4
 		fi
-
-		echo "${0##*/}: looks like invalid termination; removing lockfile"
-		echo -n $$ >/tmp/installkernel-lockfile
+		unset PID
 	fi
+
+	echo "${0##*/}: looks like invalid termination; removing lockfile"
+	echo -n $$ >/tmp/installkernel-lockfile
 fi
 
 
@@ -79,6 +80,8 @@ usage: installkernel [<options>] [<actions> [<switches>]
      --run-<event>      Synonym of  --run-pre-<event> --run-post-<hook>
 
   -c --clean            Runs 'make clean' before compilation          [no]
+  -C --config           Runs 'make (x|g|menu|)config' to configure    [no]
+  -C --config=<cfg>     Specifies a type of config to run             [auto]
   -d --make-dep         Runs 'make dep'                               [auto]
 
   -A --all              Synonym of all of the below
@@ -114,11 +117,10 @@ END
 ##
 ## Prints error and exit
 ##
-ARG0="${0##*/}"
 error () {
 	local ECODE="$1"
 	shift
-	printf "%s: %s\n" "$ARG0" "$*"
+	printf "%s: %s\n" "${0##*/}" "$*"
 	exit $ECODE
 }
 
@@ -154,13 +156,21 @@ run () {
 	local OUTPUT=/dev/stdout
 
 	# Arguments
-	[ "$1" == "-u" ] && AS=yes      && shift
-	[ "$1" == "-s" ] && SILENT=yes  && shift
-	[ "$1" == "-f" ] && FORCE=yes   && shift
-	[ "$1" == "-d" ] && DUMMY=yes   && shift
-	[ "$1" == "-i" ] && INPUT="$2"  && shift 2
-	[ "$1" == "-o" ] && OUTPUT="$2" && shift 2
-	[ "$AS" -a ! "$RUNAS" ] && AS=
+	while [ "${1:0:1}" == '-' ]; do
+		local ARG="${1:1}"; shift
+		while [ "${ARG:0}" ]; do
+			case "${ARG:0:1}" in
+				(u) AS=yes      ; ;;
+				(s) SILENT=yes  ; ;;
+				(f) FORCE=yes   ; ;;
+				(d) DUMMY=yes   ; ;;
+				(i) INPUT="$1"  ; shift; ;;
+				(o) OUTPUT="$1" ; shift; ;;
+			esac
+			ARG="${ARG:1}"
+		done
+		[ "$AS" -a ! "$RUNAS" ] && AS=
+	done
 
 	# Dry run
 	if [ "$DRY_RUN$PRINT_COMMANDS" -a ! "$SILENT" ]; then
@@ -211,8 +221,7 @@ run () {
 ##
 run_scripts () {
 	local DIR=$1
-#	eval local RUN=\$RUN_`echo $DIR | tr a-z- A-Z_`
-#	[ $RUN ] || return 0
+	eval [ \$RUN_`echo $DIR | tr a-z- A-Z_` ] || return 0
 	shift
 
 	for SCRIPT in /etc/installkernel.d/* /etc/installkernel.d/$DIR/*; do
@@ -289,7 +298,7 @@ done
 ##
 update_ver () {
 	[ $VER ] || return 0
-	run -u -f make $MAKEV include/linux/version.h
+	run -uf make $MAKEV include/linux/version.h
 	[ -f include/linux/version.h ] || error 3 include/linux/version.h: missing
 	VER=`sed -ne '/UTS_RELEASE/ s/^[^\"]*"\(.*\)"$/\1/ p' \
 	         <include/linux/version.h`
@@ -299,8 +308,8 @@ update_ver () {
 update_build () {
 	[ $BUILD ] || return 0
 	if [ ! -s .version ]; then BUILD=1; else
-		run -u -d cat .version
-		BUILD=`run -u -s -f cat .version`
+		run -ud cat .version
+		BUILD=`run -usf cat .version`
 	fi
 	echo "  BUILD   $BUILD"
 	FVER="$VER-#$BUILD"
@@ -319,12 +328,13 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 
 	export MAKE_DEP=auto CLEAN= COMPILE_IMAGE= COMPILE_MODULES=
 	export INSTALL_IMAGE=y INSTALL_MODULES= UPDATE_SYMLINKS=y
-	export UPDATE_LOADER=y TIDY_IMAGE= TIDY_MODULES=
+	export UPDATE_LOADER=y TIDY_IMAGE= TIDY_MODULES= CONFIG=
+	export CONFIG_TYPE=auto
 
 	declare -a ACTIONS
 	ACTION_COUNT=0
 
-	for EVENT in CLEAN MAKE_DEP UPDATE_SYMLINKS UPDATE_LOADER \
+	for EVENT in CLEAN CONFIG MAKE_DEP UPDATE_SYMLINKS UPDATE_LOADER \
 		{COMPILE,INSTALL,TIDY}_{IMAGE,MODULES}; do
 		eval export RUN_PRE_$EVENT=y RUN_POST_$EVENT=y
 	done
@@ -367,6 +377,11 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 			ACTION_COUNT=$(($ACTION_COUNT + 1))
 			;;
 
+		(--config=no)      CONFIG=; ;;
+		(--config=auto)    CONFIG=y; CONFIG_TYPE=auto; ;;
+		(--config=*config) CONFIG=y; CONFIG_TYPE="${1:9}"; ;;
+		(--config=*)       error 1 invalid config type: "${1:9}"; ;;
+
 		(--su) SU=y; ;;
 		(--user=*) RUNAS="${1:7}"; ;;
 		(-nu|--no-user) RUNAS=; ;;
@@ -400,6 +415,7 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 		(--color)          USE_ANSI=$VALUE; ;;
 
 		(-c|--clean)           CLEAN=$VALUE          ; ;;
+		(-C|--config)          CONFIG=$VALUE         ; ;;
 		(-d|--make-dep)        MAKE_DEP=$VALUE       ; ;;
 
 		(-i|--compile-image)   COMPILE_IMAGE=$VALUE  ; ;;
@@ -443,7 +459,7 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 
 		case "$HOOK" in
 		(hooks)
-			for EVENT in CLEAN MAKE_DEP UPDATE_SYMLINKS UPDATE_LOADER \
+			for EVENT in CLEAN CONFIG MAKE_DEP UPDATE_SYMLINKS UPDATE_LOADER \
 				{COMPILE,INSTALL,TIDY}_{IMAGE,MODULES}; do
 				if [ $PRE ]
 				then eval RUN_$PRE$EVENT=$VALUE
@@ -452,8 +468,8 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 			done
 			;;
 
-		(clean|make-dep|update-symlinks|update-loader|compile-image|install-image|tidy-image|compile-modules|install-modules|tidy-modules)
-			EVET=`echo $HOOK | tr a-z- A-Z_`
+		(clean|clean|make-dep|update-symlinks|update-loader|compile-image|install-image|tidy-image|compile-modules|install-modules|tidy-modules)
+			EVENT=`echo $HOOK | tr a-z- A-Z_`
 			if [ $PRE ]
 			then eval RUN_$PRE$EVENT=$VALUE
 			else eval RUN_PRE_$EVENT=$VALUE RUN_POST_$EVENT=$VALUE
@@ -604,9 +620,32 @@ fi
 
 
 ##
+## Check config type
+##
+if [ "$CONFIG" -a "$CONFIG_TYPE" == auto ]; then
+	if [ "$DISPLAU" ]; then
+		if   which qtconfig   >/dev/null 2>&1; then CONFIG_TYPE=xconfig
+		elif which gtk-config >/dev/null 2>&1; then CONFIG_TYPE=gconfig
+		fi
+	fi
+
+	if [ "$CONFIG_TYPE" == auto ]; then
+		for DIR in /usr/lib /usr/local/lib /lib; do
+			for LIB in curses.a curses.so ncurses.a ncurses.so; do
+				[ -f "$DIR/lib$LIB" ] && CONFIG_TYPE=menuconfig && break
+			done
+		done
+	fi
+
+	[ "$CONFIG_TYPE" == auto ] && CONFIG_TYPE=config
+fi
+
+
+##
 ## make *
 ##
 ur CLEAN           'Cleaning previous compilation' make $MAKEV clean
+ur CONFIG          'Configuring the kernel'        make $MAKEV "$CONFIG_TYPE"
 ur MAKE_DEP        'Updating dependencies'         make $MAKEV dep
 ur COMPILE_IMAGE   'Compiling bzImage'             make $MAKEV bzImage
 ur COMPILE_MODULES 'Compiling modules'             make $MAKEV modules
