+ --log and prefix options added

diff --git a/installkernel b/installkernel
--- a/installkernel
+++ b/installkernel
@@ -1,7 +1,7 @@
 #!/bin/bash
 ##
 ## installkernel - Script for installing Linux kernel.
-## $Id: installkernel,v 1.16 2005/08/18 01:45:41 mina86 Exp $
+## $Id: installkernel,v 1.17 2005/08/19 18:49:23 mina86 Exp $
 ## Copyright (c) 2004,2005 by Michal Nazarewicz (mina86/AT/tlen.pl)
 ##
 ## This program is free software; you can redistribute it and/or modify
@@ -23,8 +23,8 @@
 ## Version
 ##
 if [ ! $INSIDE_INSTALLKERNEL ]; then
-	echo 'installkernel  v0.12  (c) 2004,2005 by Micha³ Nazarewicz'
-	echo '$Id: installkernel,v 1.16 2005/08/18 01:45:41 mina86 Exp $'
+	echo 'installkernel  v0.13  (c) 2004,2005 by Micha³ Nazarewicz'
+	echo '$Id: installkernel,v 1.17 2005/08/19 18:49:23 mina86 Exp $'
 	echo
 	if [ -f /tmp/installkernel-lockfile ]; then
 		echo "${0##*/}: lockfile exists"
@@ -36,9 +36,9 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 			exit 4
 		fi
 		unset PID
+		echo "${0##*/}: looks like invalid termination; removing lockfile"
 	fi
 
-	echo "${0##*/}: looks like invalid termination; removing lockfile"
 	echo -n $$ >/tmp/installkernel-lockfile
 fi
 
@@ -49,7 +49,7 @@ fi
 usage () {
 	cat<<END
 usage: installkernel [<options>] [<actions> [<switches>]
-                     [<version> [<image> [<systemmap>]]]
+                     [<version> [<image> [<systemmap> [<prefix>]]]]
 <options> are:
   -h --help             Displays this screen and exits
   -V --version          Displays vesion and exits
@@ -60,6 +60,9 @@ usage: installkernel [<options>] [<actions> [<switches>]
   -nu --no-user         Synonym of  --user=
      --nice=<nice>      Adjust priority by <nice>                     [auto]
      --no-nice          Synonym of  --nice=0
+  -L --log=<file>       Logs everything to <file> not to stdout
+  -L --log              Logs to automaticly choosen file
+  -nL --no-log          Cancels previous --log options
 
 <actions> are:
      --cd=<dir>         Changes directory to <dir>
@@ -108,6 +111,9 @@ usage: installkernel [<options>] [<actions> [<switches>]
 <version>   kernel version (default: reads from include/linux/version.h)
 <image>     path to kernel image (default: arch/\$ARCH/boot/bzImage)
 <systemmap> path to System.map file (default: System.map)
+<prefix>    ignored
+
+See 'man 8 installkernel' for further infoormation.
 
 END
 }
@@ -118,7 +124,7 @@ END
 ## Prints error and exit
 ##
 error () {
-	local ECODE="$1"
+	ECODE="$1"
 	shift
 	printf "%s: %s\n" "${0##*/}" "$*"
 	exit $ECODE
@@ -141,6 +147,7 @@ header () {
 	done
 	date +" [%y/%m/%d %H:%M:%S] ==="
 	[ $USE_ANSI ] && echo -en '\e[0m'
+	return 0
 }
 
 
@@ -276,21 +283,36 @@ backup () {
 ## Signals etc
 ##
 interrupted () {
-	if [ $USE_ANSI ]
-	then echo -e '\e[31;1m  SIG    Got SIG'$1'; terminating...\e[0m'
-	else echo '  SIG    Got SIG$1; terminating...'
+	local EC=$?
+	if [ $1 == ERR ]; then
+		if [ $USE_ANSI ]
+		then echo -e '\e[31;1m  ERR    Command'\''s exit code: '$EC
+		else echo '  ERR    Comand'\''s exit code:'$EC
+		fi
+	else
+		if [ $USE_ANSI ]
+		then echo -e '\e[31;1m  SIG    Got SIG'$1'; terminating...\e[0m'
+		else echo '  SIG    Got SIG$1; terminating...'
+		fi
 	fi
-
-	[ -f /tmp/installkernel-$$ ]       && run rm -f /tmp/installkernel-$$
-	[ -f /tmp/installkernel-lockfile ] && run rm -f /tmp/installkernel-lockfile
 
 	exit 3
 }
 
 set -e
-for E in HUP INT QUIT ABRT SEGV PIPE ALRM TERM USR1 USR2; do
+for E in HUP INT QUIT ILL ABRT FPE SEGV PIPE ALRM TERM TSTP; do
 	trap "interrupted $E" $E
 done
+
+trap true USR1 USR2
+
+exit_function () {
+	rm -f /tmp/installkernel-$$ /tmp/installkernel-lockfile
+	[ "$LOG_AUTO" == started ] && \
+		date +'---- END ---- installkernel log file --- %y/%m/%d %H:%M:%S ---'
+}
+
+trap exit_function 0
 
 
 ##
@@ -322,6 +344,7 @@ update_build () {
 ##
 if [ ! $INSIDE_INSTALLKERNEL ]; then
 	export VER= BUILD= IMG_PATH= MAP_PATH= SU= RUNAS= NICE=auto ARCH=
+	ADD_ARGS=0
 
 	export DRY_RUN= PRINT_COMMANDS= VERBOSE= REALLY_VERBOSE=
 	[ -t ] && export USE_ANSI=y || export USE_ANSI=
@@ -354,6 +377,12 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 
 		(--arch=*) ARCH="${1:7}"; ;;
 		(-a*) ARCH="${1:2}"; ;;
+
+		(--log=*) LOG_AUTO=; LOG_FILE="${1:6}"; USE_ANSI=; ;;
+		(-L*)     LOG_AUTO=; LOG_FILE="${1:2}"; USE_ANSI=; ;;
+		(--log)   LOG_AUTO=y; USE_ANSI=; ;;
+		(-L)      LOG_AUTO=y; USE_ANSI=; ;;
+		(-nL|--no-log) LOG_AUTO=; LOG_FILE=; ;;
 
 		(--cd=*)
 			ACTIONS[$ACTION_COUNT]=cd;
@@ -395,11 +424,12 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 		(-*)     VALUE=y; PARAM="-${1:1}"; ;;
 
 		(*)
-			if   [ -z "$VER"      ]; then VER="$1"
-			elif [ -z "$IMG_PATH" ]; then IMG_PATH="$1"
-			elif [ -z "$MAP_PATH" ]; then MAP_PATH="$1"
-			else error 1 unknown option: "$1"
+			if   [ $ADD_ARGS == 0    ]; then VER="$1"
+			elif [ $ADD_ARGS == 00   ]; then IMG_PATH="$1"
+			elif [ $ADD_ARGS == 000  ]; then MAP_PATH="$1"
+			elif [ $ADD_ARGS != 0000 ]; then error 1 unknown option: "$1"
 			fi
+			ADD_ARGS="0$ADD_ARGS"
 		;;
 		esac
 
@@ -490,7 +520,25 @@ if [ ! $INSIDE_INSTALLKERNEL ]; then
 fi
 
 
-[ "$INSIDE_INSTALLKERNEL" ] ||  header Starting
+if [ ! "$INSIDE_INSTALLKERNEL" ]; then
+	if [ "$LOG_FILE" -o "$LOG_AUTO" ]; then
+		[ "$LOG_AUTO" ] && LOG_FILE=installkernel-log
+		if [ "$LOG_AUTO" -a -f "$LOG_FILE" ]; then
+			I=1
+			while [ -f "$LOG_FILE.$I" ]; do I=$(( $I + 1 )); done
+			LOG_FILE="$LOG_FILE.$I"
+		fi
+		echo "${0##*/}: logging output to '$LOG_FILE'"
+		exec >>"$LOG_FILE"
+		exec 2>&1
+		date +'--- START --- installkernel log file --- %y/%m/%d %H:%M:%S ---'
+		LOG_AUTO=started
+	fi
+
+	header Starting
+echo asd
+fi
+
 export INSIDE_INSTALLKERNEL=y
 set -- "${ACTIONS[@]}"
 unset ACTIONS ACTION_COUNT
